### PR TITLE
Feature/dakonr dx sync to

### LINKED ISSUE #77: Update `sync_from` and `sync_to` to return the diff and the status of the sync
### Environment
* DiffSync version:  1.3.0

### Proposed Functionality
Currently the functions `sync_to/from` are not returning anything, whether the sync was completed or not.
It would be useful to return at least the status of the sync and eventually the diff that was generated by the function.

### Use Case
Developer experience

### PR DESCRIPTION
**Pull request by dakonr**
- resolves #77  Improving the DX by returning the diff in the sync_to and sync_from methods.
- Added a "Raises" Paragraph to the docstring of sync_to and sync_from

### CODE REVIEW

**Review by Kircheneer — APPROVED** [review]
LGTM

**Comment by Kircheneer** [comment]
@dakonr please run black on the code and make sure the rest of the CI passes, then we're good to go. Thanks!

**Comment by dakonr** [comment]
sorry, there were still some blanks on __init__.py
should be fine now.

**Review by Kircheneer — CHANGES_REQUESTED** [review]
CI is still complaining, pylint stage this time. You can run that locally with `invoke pylint` to make sure it passes.

**Comment by dakonr** [comment]
Hi, I had to move the pylint disable comment to the first line of the function definition (in the development branch it is still at the end). 
As a new developer on the codebase I had no experience with invoke. All tasks at "invoke tests" passed on my local machine. I hope you had not that trouble with my contribution, I'm usually working with a GitLab CI toolchain.

**Review by Kircheneer — APPROVED** [review]
LGTM

**Comment by Kircheneer** [comment]
> Hi, I had to move the pylint disable comment to the first line of the function definition (in the development branch it is still at the end). As a new developer on the codebase I had no experience with invoke. All tasks at "invoke tests" passed on my local machine. I hope you had not that trouble with my contribution, I'm usually working with a GitLab CI toolchain.

@dakonr absolutely no worries - I think discoverability of the `invoke` tasks for linting is a little lacking, I will add that to the README. Thanks for the contribution!

**Pull request merged**
